/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NovoBoRouteImport } from './routes/novo-bo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DetalhesBoRouteImport } from './routes/detalhes-bo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const NovoBoRoute = NovoBoRouteImport.update({
  id: '/novo-bo',
  path: '/novo-bo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DetalhesBoRoute = DetalhesBoRouteImport.update({
  id: '/detalhes-bo',
  path: '/detalhes-bo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/detalhes-bo': typeof DetalhesBoRoute
  '/login': typeof LoginRoute
  '/novo-bo': typeof NovoBoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/detalhes-bo': typeof DetalhesBoRoute
  '/login': typeof LoginRoute
  '/novo-bo': typeof NovoBoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/detalhes-bo': typeof DetalhesBoRoute
  '/login': typeof LoginRoute
  '/novo-bo': typeof NovoBoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/detalhes-bo' | '/login' | '/novo-bo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/detalhes-bo' | '/login' | '/novo-bo'
  id: '__root__' | '/' | '/dashboard' | '/detalhes-bo' | '/login' | '/novo-bo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DetalhesBoRoute: typeof DetalhesBoRoute
  LoginRoute: typeof LoginRoute
  NovoBoRoute: typeof NovoBoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/novo-bo': {
      id: '/novo-bo'
      path: '/novo-bo'
      fullPath: '/novo-bo'
      preLoaderRoute: typeof NovoBoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detalhes-bo': {
      id: '/detalhes-bo'
      path: '/detalhes-bo'
      fullPath: '/detalhes-bo'
      preLoaderRoute: typeof DetalhesBoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DetalhesBoRoute: DetalhesBoRoute,
  LoginRoute: LoginRoute,
  NovoBoRoute: NovoBoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
